/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/rates/official/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tasa oficial vigente
         * @description Última tasa oficial BCV en estado `valid` (ADR-0007).
         */
        get: operations["getOfficialRateCurrent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rates/official/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Histórico de tasa oficial
         * @description Serie diaria de la tasa oficial por `value_date`, paginada.
         */
        get: operations["getOfficialRateHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rates/p2p/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Referencia P2P vigente
         * @description Precio de referencia P2P (Binance) para un lado del mercado.
         */
        get: operations["getP2PCurrent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/indicators/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Indicadores vigentes
         * @description Últimos indicadores derivados. La brecha, los spreads y los volúmenes
         *     provienen de la fase 2 del indicator-engine (P2P, ya implementada); vienen
         *     `null` solo mientras no haya llegado un snapshot P2P reciente.
         */
        get: operations["getIndicatorsCurrent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/indicators/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Histórico de indicadores
         * @description Serie agregada de indicadores en formato largo (una fila por
         *     indicador/moneda/instante), paginada. Rango máximo de 90 días por request.
         */
        get: operations["getIndicatorsHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Análisis de la última revisión
         * @description Lectura de los seis medidores del panel en la última revisión del
         *     indicator-engine: banda dentro de la escala de percentiles reales de la
         *     ventana (o del respaldo del ruleset, declarado en `scale.source`),
         *     posición de dibujo, y proximidad de cada regla del ruleset versionado.
         *
         *     Se devuelve **tal como se publicó** en `analysis.updated`: el gateway no
         *     reclasifica bandas ni recalcula escalas. Un análisis más viejo que la
         *     frescura P2P no se sirve como vigente (404) — nunca se presenta dato
         *     rancio como actual.
         *
         *     **No es un pronóstico**: `rule_proximity` y `summary` son aritmética
         *     sobre el estado presente (k de n condiciones y cuál bloquea). Usa el
         *     permiso `read:indicators`, el mismo que los indicadores que lee.
         */
        get: operations["getAnalysisCurrent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/depth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Profundidad del mercado P2P
         * @description Niveles de profundidad (bandas de precio y volumen acumulado) para un lado.
         */
        get: operations["getMarketDepth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Señales emitidas
         * @description Señales financieras con evidencia trazable (`inputs`, `rule`,
         *     `calc_version`), paginadas. La forma la fija el contrato `signal.v1`;
         *     `type` es string abierto por convención. El evento ya se emite (motor de
         *     reglas RF-4/ADR-0015); este endpoint devolverá datos cuando el api-gateway
         *     lea la tabla `signals`.
         */
        get: operations["getSignals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Salud del servicio
         * @description Estado por componente, sin detalles internos. Endpoint público (sin token).
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Decimal exacto no negativo, como string (nunca float).
         * @example 417.03
         */
        Decimal: string;
        /**
         * @description Decimal exacto como string; puede ser negativo (p. ej. variaciones).
         * @example -2.15
         */
        SignedDecimal: string;
        /**
         * @description Código ISO 4217.
         * @example USD
         */
        Currency: string;
        /** @description Error en formato RFC 7807, sin detalles internos. */
        Problem: {
            /**
             * Format: uri
             * @description URI que identifica el tipo de error.
             */
            type?: string;
            /** @description Resumen legible del tipo de error. */
            title: string;
            /** @description Código HTTP. */
            status: number;
            /** @description Explicación específica de esta ocurrencia (sin datos internos). */
            detail?: string;
            /**
             * Format: uri
             * @description URI de la ocurrencia (opcional).
             */
            instance?: string;
        };
        /** @description Metadatos de paginación (base 1). */
        PageMeta: {
            page: number;
            page_size: number;
            total_items?: number;
            has_more: boolean;
        };
        OfficialRateCurrent: {
            currency: components["schemas"]["Currency"];
            /** @description VES por unidad de la moneda. */
            rate: components["schemas"]["Decimal"];
            /**
             * Format: date
             * @description Fecha de vigencia de la tasa (BCV).
             */
            value_date: string;
            /**
             * Format: date-time
             * @description Instante de captura desde el BCV.
             */
            captured_at: string;
            /**
             * @description True si la **fecha-valor** de la tasa ya pasó, es decir si el BCV no
             *     ha publicado la de hoy (ADR-0022). No es una antigüedad de captura:
             *     el viernes por la tarde el BCV publica la tasa del lunes, y esa tasa
             *     está vigente todo el fin de semana.
             */
            stale: boolean;
        };
        OfficialRateHistoryItem: {
            currency: components["schemas"]["Currency"];
            rate: components["schemas"]["Decimal"];
            /** Format: date */
            value_date: string;
            /** Format: date-time */
            captured_at: string;
        };
        OfficialRateHistoryPage: {
            data: components["schemas"]["OfficialRateHistoryItem"][];
            pagination: components["schemas"]["PageMeta"];
        };
        /** @description Precio de referencia P2P para un lado del mercado. */
        P2PQuote: {
            /** @enum {string} */
            side: "buy" | "sell";
            best_price: components["schemas"]["Decimal"];
            median: components["schemas"]["Decimal"];
            /** @description Precio promedio ponderado por volumen. */
            vwap: components["schemas"]["Decimal"];
            /** @description Volumen agregado considerado en el cálculo. */
            volume: components["schemas"]["Decimal"];
            /** Format: date-time */
            as_of: string;
            /**
             * @description Confianza del snapshot (p. ej. `high`, `normal`, `low`). El
             *     vocabulario lo define el indicator-engine; nunca se sirven señales
             *     desde datos `low` confidence.
             * @example high
             */
            confidence: string;
        };
        /**
         * @description Vista de indicadores vigentes. Los campos de brecha, spreads y volúmenes
         *     (fase 2 P2P, ya implementada) vienen `null` solo mientras no haya un
         *     snapshot P2P reciente que los alimente.
         */
        Indicators: {
            currency: components["schemas"]["Currency"];
            /** Format: date-time */
            as_of: string;
            /** @description Versión de la fórmula (reproducibilidad, RF-3). */
            calc_version: number;
            /**
             * @description La fecha-valor de la tasa contra la que se calculó la brecha ya pasó
             *     (ADR-0022). Misma regla que la de `OfficialRate.stale`.
             */
            official_stale: boolean;
            /**
             * @description Brecha absoluta (P2P − oficial) en VES, del lado buy (comprar USDT
             *     con VES — la referencia de compra del paralelo, ADR-0014).
             */
            gap_abs?: components["schemas"]["SignedDecimal"] | null;
            /** @description Brecha porcentual (mismo lado buy). */
            gap_pct?: components["schemas"]["SignedDecimal"] | null;
            /**
             * @description Spread porcentual entre lados BUY↔SELL (microestructura P2P,
             *     `p2p_spread_pct` — ADR-0014).
             */
            spread_pct?: components["schemas"]["SignedDecimal"] | null;
            volumes?: {
                buy?: components["schemas"]["Decimal"];
                sell?: components["schemas"]["Decimal"];
            } | null;
        };
        /** @description Fila en formato largo de la hypertable `indicators`. */
        IndicatorHistoryItem: {
            /** Format: date-time */
            as_of: string;
            /** @description Nombre canónico (p. ej. `official_rate`, `official_rate_change_pct`). */
            indicator: string;
            currency: components["schemas"]["Currency"];
            value: components["schemas"]["SignedDecimal"];
            calc_version: number;
        };
        IndicatorHistoryPage: {
            data: components["schemas"]["IndicatorHistoryItem"][];
            pagination: components["schemas"]["PageMeta"];
            /** @enum {string} */
            interval: "5m" | "15m" | "1h" | "1d";
        };
        DepthLevel: {
            /** @description Límite (o centro) de la banda de precio. */
            price_band: components["schemas"]["Decimal"];
            /** @description Volumen acumulado hasta esta banda. */
            cum_volume: components["schemas"]["Decimal"];
        };
        MarketDepth: {
            /** @enum {string} */
            side: "buy" | "sell";
            /** Format: date-time */
            as_of: string;
            levels: components["schemas"]["DepthLevel"][];
        };
        /**
         * @description Qué hizo la brecha en las horas siguientes a la señal. **Es historia
         *     observada, no una medida de acierto**: se publica la variación y nada
         *     más — sin veredicto y sin contador agregado. El no-objetivo del PRD es no
         *     insinuar capacidad predictiva, y un «N de M» se lee como tasa de acierto.
         *
         *     Ausente mientras la ventana no se haya cumplido: eso todavía no ocurrió.
         */
        SignalOutcome: {
            /** @description Ventana observada tras la señal. */
            hours: number;
            /**
             * @description Variación de `p2p_brecha_pct_buy` en puntos porcentuales entre el
             *     instante de la señal y el final de la ventana. Ambos extremos se
             *     resuelven as-of (ADR-0009).
             */
            gap_delta_pp: components["schemas"]["SignedDecimal"];
        };
        /**
         * @description Señal financiera con evidencia trazable (T10), alineada con el contrato de
         *     evento `schemas/signal.v1.json`. El evento ya se emite y persiste (motor de
         *     reglas RF-4/ADR-0015); este recurso devolverá datos cuando el api-gateway lea
         *     la tabla `signals`.
         */
        Signal: {
            /**
             * @description Tipo de señal. Vocabulario abierto por convención (definido en `signal.v1`);
             *     catálogo canónico en `knowledge/metrics/microestructura-p2p.md`.
             */
            type: string;
            /**
             * @description Sesgo del movimiento anticipado (`neutral` = continuación/absorción).
             * @enum {string}
             */
            direction: "alcista" | "bajista" | "neutral";
            /** @description Fiat del par evaluado (ISO 4217; VES en el par USDT/VES). */
            currency: string;
            /**
             * Format: date-time
             * @description Instante del dato de mercado que disparó la regla (no la hora de emisión).
             */
            as_of: string;
            /**
             * Format: date-time
             * @description Hora de emisión (columna de la hypertable `signals`; en el evento
             *     `signal.v1` viaja como `occurred_at` del sobre).
             */
            emitted_at: string;
            calc_version: number;
            /**
             * Format: uuid
             * @description `event_id` del evento cuyos indicadores satisficieron la regla
             *     (cadena de trazabilidad, T10).
             */
            triggered_by: string;
            /** @description Insumos y regla que produjeron la señal (auditable/reproducible). */
            evidence: {
                /** @description Valores de entrada usados por la regla. */
                inputs: {
                    [key: string]: unknown;
                };
                /** @description Identificador versionado de la regla evaluada (`<type>@v<n>`). */
                rule: string;
            };
            /**
             * @description Qué hizo la brecha tras la señal. `null` mientras la ventana no se
             *     haya cumplido — o si falta alguno de los dos extremos.
             */
            outcome?: components["schemas"]["SignalOutcome"] | null;
        };
        SignalPage: {
            data: components["schemas"]["Signal"][];
            pagination: components["schemas"]["PageMeta"];
        };
        /**
         * @description Fracción en [0,1] como string exacto. **Coordenada de dibujo**, no un
         *     percentil empírico: reproducible a partir de los `cuts` del mismo payload.
         * @example 0.3140
         */
        Fraction: string;
        /** @description Un corte de la escala, con su valor real y dónde se dibuja. */
        AnalysisScaleCut: {
            /**
             * @description `p10`|`p50`|`p90` con `source: percentiles`; con `source: ruleset`,
             *     la regla versionada (`arranque_alcista@v1`) o el umbral de sistema
             *     (`confianza_baja`).
             */
            key: string;
            value: components["schemas"]["SignedDecimal"];
            position: components["schemas"]["Fraction"];
        };
        /**
         * @description La escala contra la que se leyó el medidor, con su FUENTE y sus
         *     parámetros. Que la fuente viaje en el payload es lo que permite a la UI
         *     decir contra qué se compara, en vez de degradar en silencio.
         */
        AnalysisScale: {
            /**
             * @description `percentiles` = percentiles reales de la ventana. `ruleset` =
             *     respaldo con los umbrales reales del ruleset porque
             *     `samples < min_samples`.
             * @enum {string}
             */
            source: "percentiles" | "ruleset";
            window_days: number;
            /** @description Filas encontradas en la ventana (real, también en el respaldo). */
            samples: number;
            min_samples: number;
            /**
             * @description Cuándo se calculó la distribución. Puede ir por detrás de `as_of`
             *     (se cachea con TTL); `null` si nunca se pudo consultar.
             */
            computed_at: string | null;
            /**
             * @description Extremos de la barra. Con `percentiles` son el min/max reales de la
             *     ventana; con `ruleset`, el dominio declarado en la config versionada
             *     (constante de presentación, no dato de mercado).
             */
            domain: {
                min: components["schemas"]["SignedDecimal"];
                max: components["schemas"]["SignedDecimal"];
            };
            /**
             * @description Cortes ordenados por `value` ascendente. Vacío solo en el respaldo de
             *     un indicador que no alimenta ninguna regla ni umbral de sistema.
             */
            cuts: components["schemas"]["AnalysisScaleCut"][];
        };
        /**
         * @description Una condición del ruleset que consume ESTE indicador, con cuánto le falta
         *     al valor para satisfacerla.
         */
        AnalysisRuleRef: {
            /** @description Regla versionada `<type>@v<n>` (mismo id que `Signal.evidence.rule`). */
            rule: string;
            type: string;
            /** @enum {string} */
            direction: "alcista" | "bajista" | "neutral";
            /** @enum {string} */
            op: "gt" | "gte" | "lt" | "lte";
            threshold: components["schemas"]["SignedDecimal"];
            met: boolean;
            /**
             * @description Cuánto debe moverse el valor EN LA DIRECCIÓN EXIGIDA:
             *     `threshold - value` con gt/gte, `value - threshold` con lt/lte.
             *     `<= 0` significa satisfecha. Nunca es una predicción de cuándo pasará.
             */
            distance: components["schemas"]["SignedDecimal"];
            threshold_position: components["schemas"]["Fraction"];
        };
        /**
         * @description La lectura de un medidor. Un indicador sin valor vigente NO aparece en el
         *     array: nunca se infiere.
         */
        AnalysisIndicator: {
            /** @description Nombre canónico (`knowledge/metrics/`). No se traduce. */
            indicator: string;
            value: components["schemas"]["SignedDecimal"];
            /** Format: date-time */
            as_of: string;
            /**
             * @description Vocabulario neutro de idioma; la prosa la redacta el cliente.
             *     Con percentiles: `very_low` <p10 · `low` [p10,p50) · `high` [p50,p90)
             *     · `very_high` >=p90. `unscaled` con el respaldo del ruleset: sin
             *     distribución empírica no existe alto/bajo, y emitir ahí una banda
             *     sería inventar dato.
             * @enum {string}
             */
            band: "very_low" | "low" | "high" | "very_high" | "unscaled";
            /** @description `null` cuando no hay escala dibujable: nada que pintar. */
            position: components["schemas"]["Fraction"] | null;
            scale: components["schemas"]["AnalysisScale"];
            /** @description Vacío si el indicador no alimenta ninguna condición. */
            rules: components["schemas"]["AnalysisRuleRef"][];
        };
        RuleCondition: {
            indicator: string;
            /** @enum {string} */
            op: "gt" | "gte" | "lt" | "lte";
            threshold: components["schemas"]["SignedDecimal"];
            /**
             * @description `null` si el indicador no está vigente. Nunca se rellena con el
             *     último conocido rancio.
             */
            value: components["schemas"]["SignedDecimal"] | null;
            met: boolean;
            distance: components["schemas"]["SignedDecimal"] | null;
        };
        /**
         * @description Cuántas condiciones de una regla se cumplen y cuál bloquea. Aritmética
         *     sobre el estado presente, NO un pronóstico ni un régimen.
         */
        RuleProximity: {
            rule: string;
            type: string;
            /** @enum {string} */
            direction: "alcista" | "bajista" | "neutral";
            conditions_total: number;
            conditions_met: number;
            /**
             * @description `false` si algún indicador de la regla no está vigente (mismo criterio
             *     que la emisión: una regla con un indicador ausente no dispara) o si
             *     `confidence: low`.
             */
            evaluable: boolean;
            /**
             * @description Indicador de la condición NO cumplida con mayor `distance`; empate por
             *     orden alfabético. `null` si la regla se cumple entera o no es evaluable.
             */
            blocked_by: string | null;
            conditions: components["schemas"]["RuleCondition"][];
        };
        /**
         * @description Síntesis MECÁNICA del panel: qué regla está más cerca de cumplirse y qué
         *     la bloquea. Sin probabilidades, sin horizontes temporales, sin régimen.
         */
        AnalysisSummary: {
            rules_total: number;
            rules_evaluable: number;
            /**
             * @description Entre las evaluables no cumplidas: la de mayor `conditions_met`;
             *     empate por menor `conditions_total` y luego orden alfabético. `null`
             *     si ninguna es evaluable o todas se cumplen.
             */
            closest_rule: string | null;
            /** @description Condiciones cumplidas de `closest_rule` (0 si no hay ninguna). */
            conditions_met: number;
            conditions_total: number;
            blocked_by: string | null;
            /**
             * @description Reglas con TODAS sus condiciones cumplidas en esta revisión. NO
             *     implica que la señal se emitiera: el cooldown pudo suprimirla. La
             *     emisión real vive en `/signals`.
             */
            rules_met: string[];
        };
        /**
         * @description Una afirmación de la lectura, en vocabulario neutro de idioma. La prosa
         *     ES/EN la redacta el cliente.
         */
        ReadingClaim: {
            /**
             * @description `atribucion` solo aparece si la brecha se movió **y** la oficial no
             *     está rancia: con una tasa vencida, decir quién movió la brecha sería
             *     afirmar de más.
             *
             *     `historia_parcial` aparece **en lugar de** `brecha_vs_historia`
             *     cuando ninguna ventana alcanza su cobertura: es lo que impide leer
             *     una media de 12 días como si fuera de 90.
             * @enum {string}
             */
            code: "confianza_baja" | "oficial_rancia" | "brecha" | "atribucion" | "medidor_en_banda" | "regla_cerca" | "brecha_vs_historia" | "brecha_extremo" | "historia_parcial";
            /**
             * @description Cifras y cualificadores, como string exacto. Claves según el código:
             *     `brecha` → {direccion, delta_pp, horas} · `atribucion` →
             *     {responsable, paralelo, oficial} · `medidor_en_banda` →
             *     {indicador, banda, dias} · `regla_cerca` → {regla, cumplidas, totales}.
             */
            data: {
                [key: string]: string;
            };
        };
        /**
         * @description Lectura del estado de mercado (ADR-0021). Describe el **presente**: el
         *     régimen es la celda de una matriz de dos ejes clasificados por umbrales
         *     de config versionada, no una anticipación de lo que viene. **No contiene
         *     consejo**: ninguna afirmación dice qué hacer.
         */
        MarketReading: {
            /** @description Versión de la config de lectura (umbrales, ventana, dominancia). */
            version: number;
            window_hours: number;
            /**
             * @description `<axis_movement>_<axis_gap>`, p. ej. `lateral_comprimiendo`. `null` si
             *     cualquiera de los dos ejes no resolvió — media clasificación no se
             *     publica, porque «lateral» a secas daría a entender que la brecha está
             *     quieta cuando no se sabe.
             */
            regime: string | null;
            axis_movement: ("subiendo" | "lateral" | "bajando") | null;
            axis_gap: ("ampliando" | "estable" | "comprimiendo") | null;
            /**
             * @description Medidores con algún umbral sin cruzar a tiro de piedra, medido en
             *     coordenadas de dibujo — normalizar es lo único que hace comparable un
             *     porcentaje de brecha con un ratio.
             */
            gauges_near_threshold: number;
            /** @description En ORDEN de lectura; lo que invalida al resto va primero. */
            claims: components["schemas"]["ReadingClaim"][];
        };
        /**
         * @description Lectura de los medidores del panel en una revisión (ADR-0019). Es el
         *     `payload` del evento `analysis.updated`, servido verbatim.
         */
        IndicatorAnalysis: {
            /**
             * Format: date-time
             * @description Instante del dato de mercado de la revisión, no la hora de emisión.
             */
            as_of: string;
            currency: components["schemas"]["Currency"];
            calc_version: number;
            /** @description Versión de la config de análisis (ventana, cortes, dominios). */
            analysis_version: number;
            ruleset_version: number;
            /**
             * @description `low` = > 30 % de outliers en el snapshot: las señales se suprimen y
             *     ninguna regla es evaluable.
             * @enum {string}
             */
            confidence: "normal" | "low";
            official_stale: boolean;
            /** @description `event_id` del `p2p.snapshot` que produjo la revisión (T10). */
            triggered_by: string;
            indicators: components["schemas"]["AnalysisIndicator"][];
            rule_proximity: components["schemas"]["RuleProximity"][];
            summary: components["schemas"]["AnalysisSummary"];
            reading?: components["schemas"]["MarketReading"];
            gap_history?: components["schemas"]["GapHistory"];
            gap_legs?: components["schemas"]["GapLegs"];
        };
        /**
         * @description Las dos piernas que explican el movimiento de la brecha sobre la ventana
         *     de lectura (ADR-0023). Se publica SIEMPRE que las variaciones sean
         *     medibles, aunque no haya atribución: las deltas son hechos, mientras que
         *     decir QUIÉN movió la brecha necesita que la brecha se haya movido y que
         *     la tasa oficial esté vigente (ADR-0022). Por eso `responsible` puede ser
         *     null con `official` y `parallel` presentes.
         *
         *     En VES ABSOLUTOS: es la única unidad donde `Δbrecha = Δparalelo −
         *     Δoficial` es exacta. El neto NO viaja — el consumidor lo deriva de esa
         *     identidad, en vez de recibir una tercera medición que podría no cuadrar
         *     con las otras dos en pantalla.
         */
        GapLegs: {
            /** @description Ventana medida, en horas. La misma del claim `brecha`. */
            hours: number;
            /**
             * @description Δ de la tasa oficial en VES. `0` es un dato, no un hueco: el BCV
             *     publica por tramos y una meseta significa que no cambió.
             */
            official: components["schemas"]["SignedDecimal"] | null;
            /**
             * @description Δ del paralelo (VWAP buy) en VES. null si hubo hueco de captura: ahí
             *     la variación no es comparable y no se estira.
             */
            parallel: components["schemas"]["SignedDecimal"] | null;
            /**
             * @description Qué pierna movió la brecha, o null si no se puede afirmar. La decide
             *     el motor: recalcularla en el cliente crearía una segunda fuente de
             *     verdad.
             */
            responsible: ("paralelo" | "oficial" | "ambos") | null;
            /**
             * @description Cuota del MOVIMIENTO total que puso la tasa oficial, en [0, 1]:
             *     `|Δoficial| / (|Δoficial| + |Δparalelo|)`. Es el mismo número con el
             *     que el motor decide `responsible`, y por eso se publica en vez de
             *     recalcularse.
             *
             *     NO es «cuota del cierre»: con las dos piernas subiendo, la oficial
             *     cierra la brecha y el paralelo la abre, así que del cierre la oficial
             *     pone el 100 %. null si nada se movió o alguna pierna no es medible.
             */
            official_share: components["schemas"]["Decimal"] | null;
        };
        /**
         * @description Una ventana de comparación. `days_covered` es el mecanismo de honestidad:
         *     cuando es menor que `days_configured`, la serie NO alcanza la ventana
         *     pedida y la UI debe rotular el tramo real («Promedio 12 d de 30») en vez
         *     de la etiqueta nominal. Mismo criterio que `scale.samples`/`min_samples`
         *     en los medidores.
         */
        GapHistoryReference: {
            /** @description La ventana que se pidió. */
            days_configured: number;
            /** @description Hasta dónde llega la serie DENTRO de esa ventana. */
            days_covered: number;
            samples: number;
            mean: components["schemas"]["SignedDecimal"] | null;
            max: components["schemas"]["SignedDecimal"] | null;
            min: components["schemas"]["SignedDecimal"] | null;
        };
        GapHistorySide: {
            /** @enum {string} */
            side: "buy" | "sell";
            /** @description La brecha de hoy, la MISMA cifra que publica el resto del análisis. */
            current: components["schemas"]["SignedDecimal"] | null;
            /** @description Una por ventana configurada, en orden creciente. Se publican todas, completas o no. */
            references: components["schemas"]["GapHistoryReference"][];
        };
        /**
         * @description La brecha de cada lado contra su propia historia (RF-7, ADR-0021).
         *     Aditivo y opcional. Viaja en el mismo documento que el análisis por la
         *     misma razón que `reading`: la tarjeta cita a la vez el valor de hoy y sus
         *     referencias, así que tienen que ser atómicamente coherentes.
         *
         *     El lado **venta** tiene historia real desde 2025-12 (derivada de un export
         *     externo, ver ADR-0013 RF-7); el de **compra**, solo desde que el motor
         *     arrancó. Por eso `days_covered` no es decorativo.
         */
        GapHistory: {
            /** @description Un elemento por lado con datos; un lado sin serie no aparece. */
            sides: components["schemas"]["GapHistorySide"][];
        };
        /** @description Estado agregado y por componente, sin detalles internos. */
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded" | "down";
            /** @description Estado por componente (p. ej. `database`, `broker`, `auth`). */
            components?: {
                [key: string]: "ok" | "degraded" | "down";
            };
        };
    };
    responses: {
        /** @description Parámetros inválidos. */
        BadRequest: {
            headers: {
                "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.vesmarketwatch/errors/invalid-parameter",
                 *       "title": "Parámetro inválido",
                 *       "status": 400,
                 *       "detail": "El parámetro 'side' debe ser 'buy' o 'sell'."
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Falta el token, está expirado o su firma/claims no validan. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.vesmarketwatch/errors/unauthorized",
                 *       "title": "No autenticado",
                 *       "status": 401,
                 *       "detail": "Access token ausente o inválido."
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description El token es válido pero carece del permiso requerido. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.vesmarketwatch/errors/forbidden",
                 *       "title": "Permiso insuficiente",
                 *       "status": 403,
                 *       "detail": "Se requiere el permiso 'read:signals'."
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description El recurso aún no tiene datos que servir. */
        NotFound: {
            headers: {
                "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.vesmarketwatch/errors/not-found",
                 *       "title": "Sin datos",
                 *       "status": 404,
                 *       "detail": "Sin tasa oficial registrada para USD."
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Rango de fechas inválido o mayor a 90 días. */
        UnprocessableRange: {
            headers: {
                "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.vesmarketwatch/errors/range-too-large",
                 *       "title": "Rango no procesable",
                 *       "status": 422,
                 *       "detail": "El rango solicitado excede el máximo de 90 días."
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Se superó el límite de peticiones. */
        TooManyRequests: {
            headers: {
                /** @description Segundos hasta poder reintentar. */
                "Retry-After"?: number;
                "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.vesmarketwatch/errors/rate-limited",
                 *       "title": "Demasiadas peticiones",
                 *       "status": 429,
                 *       "detail": "Límite de peticiones superado; reintente más tarde."
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Número de página (base 1). */
        Page: number;
        /** @description Tamaño de página. */
        PageSize: number;
        /**
         * @description Inicio del rango (fecha, inclusive).
         * @example 2026-04-18
         */
        FromDate: string;
        /**
         * @description Fin del rango (fecha, inclusive). Rango máximo de 90 días.
         * @example 2026-07-17
         */
        ToDate: string;
        /**
         * @description Inicio del rango (RFC 3339, inclusive).
         * @example 2026-07-10T00:00:00Z
         */
        FromDateTime: string;
        /**
         * @description Fin del rango (RFC 3339, inclusive). Rango máximo de 90 días.
         * @example 2026-07-17T00:00:00Z
         */
        ToDateTime: string;
        /** @description Lado del mercado. */
        Side: "buy" | "sell";
        /** @description Granularidad de agregación. */
        Interval: "5m" | "15m" | "1h" | "1d";
        /** @description Código ISO 4217 de la moneda base (frente a VES). */
        Currency: string;
        /**
         * @description Filtra la serie por nombre canónico de indicador (p. ej.
         *     `p2p_brecha_pct_buy`). Sin el filtro se devuelve el formato largo
         *     completo — para gráficos de UN indicador, usar SIEMPRE este filtro
         *     (evita paginar toda la tabla y agotar la cuota).
         */
        IndicatorName: string;
        /**
         * @description Fiat del par sobre el que se leyó el panel. Los indicadores `p2p_*` se
         *     persisten bajo el fiat (`VES`), no bajo la pierna oficial (ADR-0014).
         */
        CurrencyP2P: string;
        /**
         * @description Filtra por moneda del indicador (los `p2p_*` viven bajo `VES`; los
         *     `official_rate*` bajo su moneda BCV). Sin default: sin el filtro se
         *     devuelven todas las monedas.
         */
        CurrencyFilter: string;
        /**
         * @description Filtro por tipo de señal. Vocabulario abierto por convención (definido en
         *     `signal.v1`); catálogo en `knowledge/metrics/microestructura-p2p.md`.
         */
        SignalType: string;
    };
    requestBodies: never;
    headers: {
        /** @description Cuota de peticiones en la ventana actual. */
        XRateLimitLimit: number;
        /** @description Peticiones restantes en la ventana actual. */
        XRateLimitRemaining: number;
        /** @description Epoch (segundos UTC) en que se reinicia la ventana. */
        XRateLimitReset: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getOfficialRateCurrent: {
        parameters: {
            query?: {
                /** @description Código ISO 4217 de la moneda base (frente a VES). */
                currency?: components["parameters"]["Currency"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tasa oficial vigente. */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfficialRateCurrent"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getOfficialRateHistory: {
        parameters: {
            query: {
                /**
                 * @description Inicio del rango (fecha, inclusive).
                 * @example 2026-04-18
                 */
                from: components["parameters"]["FromDate"];
                /**
                 * @description Fin del rango (fecha, inclusive). Rango máximo de 90 días.
                 * @example 2026-07-17
                 */
                to: components["parameters"]["ToDate"];
                /** @description Código ISO 4217 de la moneda base (frente a VES). */
                currency?: components["parameters"]["Currency"];
                /** @description Número de página (base 1). */
                page?: components["parameters"]["Page"];
                /** @description Tamaño de página. */
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de tasas oficiales históricas. */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfficialRateHistoryPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableRange"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getP2PCurrent: {
        parameters: {
            query: {
                /** @description Lado del mercado. */
                side: components["parameters"]["Side"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Referencia P2P vigente para el lado solicitado. */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["P2PQuote"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getIndicatorsCurrent: {
        parameters: {
            query?: {
                /** @description Código ISO 4217 de la moneda base (frente a VES). */
                currency?: components["parameters"]["Currency"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Indicadores vigentes. */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Indicators"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getIndicatorsHistory: {
        parameters: {
            query: {
                /**
                 * @description Inicio del rango (RFC 3339, inclusive).
                 * @example 2026-07-10T00:00:00Z
                 */
                from: components["parameters"]["FromDateTime"];
                /**
                 * @description Fin del rango (RFC 3339, inclusive). Rango máximo de 90 días.
                 * @example 2026-07-17T00:00:00Z
                 */
                to: components["parameters"]["ToDateTime"];
                /** @description Granularidad de agregación. */
                interval?: components["parameters"]["Interval"];
                /**
                 * @description Filtra la serie por nombre canónico de indicador (p. ej.
                 *     `p2p_brecha_pct_buy`). Sin el filtro se devuelve el formato largo
                 *     completo — para gráficos de UN indicador, usar SIEMPRE este filtro
                 *     (evita paginar toda la tabla y agotar la cuota).
                 */
                indicator?: components["parameters"]["IndicatorName"];
                /**
                 * @description Filtra por moneda del indicador (los `p2p_*` viven bajo `VES`; los
                 *     `official_rate*` bajo su moneda BCV). Sin default: sin el filtro se
                 *     devuelven todas las monedas.
                 */
                currency?: components["parameters"]["CurrencyFilter"];
                /** @description Número de página (base 1). */
                page?: components["parameters"]["Page"];
                /** @description Tamaño de página. */
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de indicadores históricos. */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndicatorHistoryPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableRange"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getAnalysisCurrent: {
        parameters: {
            query?: {
                /**
                 * @description Fiat del par sobre el que se leyó el panel. Los indicadores `p2p_*` se
                 *     persisten bajo el fiat (`VES`), no bajo la pierna oficial (ADR-0014).
                 */
                currency?: components["parameters"]["CurrencyP2P"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Análisis vigente. */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndicatorAnalysis"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getMarketDepth: {
        parameters: {
            query: {
                /** @description Lado del mercado. */
                side: components["parameters"]["Side"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profundidad del mercado para el lado solicitado. */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketDepth"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getSignals: {
        parameters: {
            query: {
                /**
                 * @description Inicio del rango (RFC 3339, inclusive).
                 * @example 2026-07-10T00:00:00Z
                 */
                from: components["parameters"]["FromDateTime"];
                /**
                 * @description Fin del rango (RFC 3339, inclusive). Rango máximo de 90 días.
                 * @example 2026-07-17T00:00:00Z
                 */
                to: components["parameters"]["ToDateTime"];
                /**
                 * @description Filtro por tipo de señal. Vocabulario abierto por convención (definido en
                 *     `signal.v1`); catálogo en `knowledge/metrics/microestructura-p2p.md`.
                 */
                type?: components["parameters"]["SignalType"];
                /** @description Número de página (base 1). */
                page?: components["parameters"]["Page"];
                /** @description Tamaño de página. */
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de señales. */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableRange"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description El servicio está operativo (posiblemente degradado). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description El servicio no está operativo. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
