/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/rates/official/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tasa oficial vigente
         * @description Última tasa oficial BCV en estado `valid` (ADR-0007).
         */
        get: operations["getOfficialRateCurrent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rates/official/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Histórico de tasa oficial
         * @description Serie diaria de la tasa oficial por `value_date`, paginada.
         */
        get: operations["getOfficialRateHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rates/p2p/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Referencia P2P vigente
         * @description Precio de referencia P2P (Binance) para un lado del mercado.
         */
        get: operations["getP2PCurrent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/indicators/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Indicadores vigentes
         * @description Últimos indicadores derivados. La brecha, los spreads y los volúmenes
         *     provienen de la fase 2 del indicator-engine (P2P, ya implementada); vienen
         *     `null` solo mientras no haya llegado un snapshot P2P reciente.
         */
        get: operations["getIndicatorsCurrent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/indicators/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Histórico de indicadores
         * @description Serie agregada de indicadores en formato largo (una fila por
         *     indicador/moneda/instante), paginada. Rango máximo de 90 días por request.
         */
        get: operations["getIndicatorsHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/depth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Profundidad del mercado P2P
         * @description Niveles de profundidad (bandas de precio y volumen acumulado) para un lado.
         */
        get: operations["getMarketDepth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Señales emitidas
         * @description Señales financieras con evidencia trazable (`inputs`, `rule`,
         *     `calc_version`), paginadas. La forma la fija el contrato `signal.v1`;
         *     `type` es string abierto por convención. El evento ya se emite (motor de
         *     reglas RF-4/ADR-0015); este endpoint devolverá datos cuando el api-gateway
         *     lea la tabla `signals`.
         */
        get: operations["getSignals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Salud del servicio
         * @description Estado por componente, sin detalles internos. Endpoint público (sin token).
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Decimal exacto no negativo, como string (nunca float).
         * @example 417.03
         */
        Decimal: string;
        /**
         * @description Decimal exacto como string; puede ser negativo (p. ej. variaciones).
         * @example -2.15
         */
        SignedDecimal: string;
        /**
         * @description Código ISO 4217.
         * @example USD
         */
        Currency: string;
        /** @description Error en formato RFC 7807, sin detalles internos. */
        Problem: {
            /**
             * Format: uri
             * @description URI que identifica el tipo de error.
             */
            type?: string;
            /** @description Resumen legible del tipo de error. */
            title: string;
            /** @description Código HTTP. */
            status: number;
            /** @description Explicación específica de esta ocurrencia (sin datos internos). */
            detail?: string;
            /**
             * Format: uri
             * @description URI de la ocurrencia (opcional).
             */
            instance?: string;
        };
        /** @description Metadatos de paginación (base 1). */
        PageMeta: {
            page: number;
            page_size: number;
            total_items?: number;
            has_more: boolean;
        };
        OfficialRateCurrent: {
            currency: components["schemas"]["Currency"];
            /** @description VES por unidad de la moneda. */
            rate: components["schemas"]["Decimal"];
            /**
             * Format: date
             * @description Fecha de vigencia de la tasa (BCV).
             */
            value_date: string;
            /**
             * Format: date-time
             * @description Instante de captura desde el BCV.
             */
            captured_at: string;
            /** @description True si la tasa vigente supera el umbral de frescura. */
            stale: boolean;
        };
        OfficialRateHistoryItem: {
            currency: components["schemas"]["Currency"];
            rate: components["schemas"]["Decimal"];
            /** Format: date */
            value_date: string;
            /** Format: date-time */
            captured_at: string;
        };
        OfficialRateHistoryPage: {
            data: components["schemas"]["OfficialRateHistoryItem"][];
            pagination: components["schemas"]["PageMeta"];
        };
        /** @description Precio de referencia P2P para un lado del mercado. */
        P2PQuote: {
            /** @enum {string} */
            side: "buy" | "sell";
            best_price: components["schemas"]["Decimal"];
            median: components["schemas"]["Decimal"];
            /** @description Precio promedio ponderado por volumen. */
            vwap: components["schemas"]["Decimal"];
            /** @description Volumen agregado considerado en el cálculo. */
            volume: components["schemas"]["Decimal"];
            /** Format: date-time */
            as_of: string;
            /**
             * @description Confianza del snapshot (p. ej. `high`, `normal`, `low`). El
             *     vocabulario lo define el indicator-engine; nunca se sirven señales
             *     desde datos `low` confidence.
             * @example high
             */
            confidence: string;
        };
        /**
         * @description Vista de indicadores vigentes. Los campos de brecha, spreads y volúmenes
         *     (fase 2 P2P, ya implementada) vienen `null` solo mientras no haya un
         *     snapshot P2P reciente que los alimente.
         */
        Indicators: {
            currency: components["schemas"]["Currency"];
            /** Format: date-time */
            as_of: string;
            /** @description Versión de la fórmula (reproducibilidad, RF-3). */
            calc_version: number;
            official_stale: boolean;
            /**
             * @description Brecha absoluta (P2P − oficial) en VES, del lado buy (comprar USDT
             *     con VES — la referencia de compra del paralelo, ADR-0014).
             */
            gap_abs?: components["schemas"]["SignedDecimal"] | null;
            /** @description Brecha porcentual (mismo lado buy). */
            gap_pct?: components["schemas"]["SignedDecimal"] | null;
            /**
             * @description Spread porcentual entre lados BUY↔SELL (microestructura P2P,
             *     `p2p_spread_pct` — ADR-0014).
             */
            spread_pct?: components["schemas"]["SignedDecimal"] | null;
            volumes?: {
                buy?: components["schemas"]["Decimal"];
                sell?: components["schemas"]["Decimal"];
            } | null;
        };
        /** @description Fila en formato largo de la hypertable `indicators`. */
        IndicatorHistoryItem: {
            /** Format: date-time */
            as_of: string;
            /** @description Nombre canónico (p. ej. `official_rate`, `official_rate_change_pct`). */
            indicator: string;
            currency: components["schemas"]["Currency"];
            value: components["schemas"]["SignedDecimal"];
            calc_version: number;
        };
        IndicatorHistoryPage: {
            data: components["schemas"]["IndicatorHistoryItem"][];
            pagination: components["schemas"]["PageMeta"];
            /** @enum {string} */
            interval: "5m" | "1h" | "1d";
        };
        DepthLevel: {
            /** @description Límite (o centro) de la banda de precio. */
            price_band: components["schemas"]["Decimal"];
            /** @description Volumen acumulado hasta esta banda. */
            cum_volume: components["schemas"]["Decimal"];
        };
        MarketDepth: {
            /** @enum {string} */
            side: "buy" | "sell";
            /** Format: date-time */
            as_of: string;
            levels: components["schemas"]["DepthLevel"][];
        };
        /**
         * @description Señal financiera con evidencia trazable (T10), alineada con el contrato de
         *     evento `schemas/signal.v1.json`. El evento ya se emite y persiste (motor de
         *     reglas RF-4/ADR-0015); este recurso devolverá datos cuando el api-gateway lea
         *     la tabla `signals`.
         */
        Signal: {
            /**
             * @description Tipo de señal. Vocabulario abierto por convención (definido en `signal.v1`);
             *     catálogo canónico en `knowledge/metrics/microestructura-p2p.md`.
             */
            type: string;
            /**
             * @description Sesgo del movimiento anticipado (`neutral` = continuación/absorción).
             * @enum {string}
             */
            direction: "alcista" | "bajista" | "neutral";
            /** @description Fiat del par evaluado (ISO 4217; VES en el par USDT/VES). */
            currency: string;
            /**
             * Format: date-time
             * @description Instante del dato de mercado que disparó la regla (no la hora de emisión).
             */
            as_of: string;
            /**
             * Format: date-time
             * @description Hora de emisión (columna de la hypertable `signals`; en el evento
             *     `signal.v1` viaja como `occurred_at` del sobre).
             */
            emitted_at: string;
            calc_version: number;
            /**
             * Format: uuid
             * @description `event_id` del evento cuyos indicadores satisficieron la regla
             *     (cadena de trazabilidad, T10).
             */
            triggered_by: string;
            /** @description Insumos y regla que produjeron la señal (auditable/reproducible). */
            evidence: {
                /** @description Valores de entrada usados por la regla. */
                inputs: {
                    [key: string]: unknown;
                };
                /** @description Identificador versionado de la regla evaluada (`<type>@v<n>`). */
                rule: string;
            };
        };
        SignalPage: {
            data: components["schemas"]["Signal"][];
            pagination: components["schemas"]["PageMeta"];
        };
        /** @description Estado agregado y por componente, sin detalles internos. */
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded" | "down";
            /** @description Estado por componente (p. ej. `database`, `broker`, `auth`). */
            components?: {
                [key: string]: "ok" | "degraded" | "down";
            };
        };
    };
    responses: {
        /** @description Parámetros inválidos. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.vesmarketwatch/errors/invalid-parameter",
                 *       "title": "Parámetro inválido",
                 *       "status": 400,
                 *       "detail": "El parámetro 'side' debe ser 'buy' o 'sell'."
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Falta el token, está expirado o su firma/claims no validan. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.vesmarketwatch/errors/unauthorized",
                 *       "title": "No autenticado",
                 *       "status": 401,
                 *       "detail": "Access token ausente o inválido."
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description El token es válido pero carece del permiso requerido. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.vesmarketwatch/errors/forbidden",
                 *       "title": "Permiso insuficiente",
                 *       "status": 403,
                 *       "detail": "Se requiere el permiso 'read:signals'."
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description El recurso aún no tiene datos que servir. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.vesmarketwatch/errors/not-found",
                 *       "title": "Sin datos",
                 *       "status": 404,
                 *       "detail": "Sin tasa oficial registrada para USD."
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Rango de fechas inválido o mayor a 90 días. */
        UnprocessableRange: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.vesmarketwatch/errors/range-too-large",
                 *       "title": "Rango no procesable",
                 *       "status": 422,
                 *       "detail": "El rango solicitado excede el máximo de 90 días."
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Se superó el límite de peticiones. */
        TooManyRequests: {
            headers: {
                /** @description Segundos hasta poder reintentar. */
                "Retry-After"?: number;
                "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.vesmarketwatch/errors/rate-limited",
                 *       "title": "Demasiadas peticiones",
                 *       "status": 429,
                 *       "detail": "Límite de peticiones superado; reintente más tarde."
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Número de página (base 1). */
        Page: number;
        /** @description Tamaño de página. */
        PageSize: number;
        /**
         * @description Inicio del rango (fecha, inclusive).
         * @example 2026-04-18
         */
        FromDate: string;
        /**
         * @description Fin del rango (fecha, inclusive). Rango máximo de 90 días.
         * @example 2026-07-17
         */
        ToDate: string;
        /**
         * @description Inicio del rango (RFC 3339, inclusive).
         * @example 2026-07-10T00:00:00Z
         */
        FromDateTime: string;
        /**
         * @description Fin del rango (RFC 3339, inclusive). Rango máximo de 90 días.
         * @example 2026-07-17T00:00:00Z
         */
        ToDateTime: string;
        /** @description Lado del mercado. */
        Side: "buy" | "sell";
        /** @description Granularidad de agregación. */
        Interval: "5m" | "1h" | "1d";
        /** @description Código ISO 4217 de la moneda base (frente a VES). */
        Currency: string;
        /**
         * @description Filtra la serie por nombre canónico de indicador (p. ej.
         *     `p2p_brecha_pct_buy`). Sin el filtro se devuelve el formato largo
         *     completo — para gráficos de UN indicador, usar SIEMPRE este filtro
         *     (evita paginar toda la tabla y agotar la cuota).
         */
        IndicatorName: string;
        /**
         * @description Filtra por moneda del indicador (los `p2p_*` viven bajo `VES`; los
         *     `official_rate*` bajo su moneda BCV). Sin default: sin el filtro se
         *     devuelven todas las monedas.
         */
        CurrencyFilter: string;
        /**
         * @description Filtro por tipo de señal. Vocabulario abierto por convención (definido en
         *     `signal.v1`); catálogo en `knowledge/metrics/microestructura-p2p.md`.
         */
        SignalType: string;
    };
    requestBodies: never;
    headers: {
        /** @description Cuota de peticiones en la ventana actual. */
        XRateLimitLimit: number;
        /** @description Peticiones restantes en la ventana actual. */
        XRateLimitRemaining: number;
        /** @description Epoch (segundos UTC) en que se reinicia la ventana. */
        XRateLimitReset: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getOfficialRateCurrent: {
        parameters: {
            query?: {
                /** @description Código ISO 4217 de la moneda base (frente a VES). */
                currency?: components["parameters"]["Currency"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tasa oficial vigente. */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfficialRateCurrent"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getOfficialRateHistory: {
        parameters: {
            query: {
                /**
                 * @description Inicio del rango (fecha, inclusive).
                 * @example 2026-04-18
                 */
                from: components["parameters"]["FromDate"];
                /**
                 * @description Fin del rango (fecha, inclusive). Rango máximo de 90 días.
                 * @example 2026-07-17
                 */
                to: components["parameters"]["ToDate"];
                /** @description Código ISO 4217 de la moneda base (frente a VES). */
                currency?: components["parameters"]["Currency"];
                /** @description Número de página (base 1). */
                page?: components["parameters"]["Page"];
                /** @description Tamaño de página. */
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de tasas oficiales históricas. */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfficialRateHistoryPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableRange"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getP2PCurrent: {
        parameters: {
            query: {
                /** @description Lado del mercado. */
                side: components["parameters"]["Side"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Referencia P2P vigente para el lado solicitado. */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["P2PQuote"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getIndicatorsCurrent: {
        parameters: {
            query?: {
                /** @description Código ISO 4217 de la moneda base (frente a VES). */
                currency?: components["parameters"]["Currency"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Indicadores vigentes. */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Indicators"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getIndicatorsHistory: {
        parameters: {
            query: {
                /**
                 * @description Inicio del rango (RFC 3339, inclusive).
                 * @example 2026-07-10T00:00:00Z
                 */
                from: components["parameters"]["FromDateTime"];
                /**
                 * @description Fin del rango (RFC 3339, inclusive). Rango máximo de 90 días.
                 * @example 2026-07-17T00:00:00Z
                 */
                to: components["parameters"]["ToDateTime"];
                /** @description Granularidad de agregación. */
                interval?: components["parameters"]["Interval"];
                /**
                 * @description Filtra la serie por nombre canónico de indicador (p. ej.
                 *     `p2p_brecha_pct_buy`). Sin el filtro se devuelve el formato largo
                 *     completo — para gráficos de UN indicador, usar SIEMPRE este filtro
                 *     (evita paginar toda la tabla y agotar la cuota).
                 */
                indicator?: components["parameters"]["IndicatorName"];
                /**
                 * @description Filtra por moneda del indicador (los `p2p_*` viven bajo `VES`; los
                 *     `official_rate*` bajo su moneda BCV). Sin default: sin el filtro se
                 *     devuelven todas las monedas.
                 */
                currency?: components["parameters"]["CurrencyFilter"];
                /** @description Número de página (base 1). */
                page?: components["parameters"]["Page"];
                /** @description Tamaño de página. */
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de indicadores históricos. */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndicatorHistoryPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableRange"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getMarketDepth: {
        parameters: {
            query: {
                /** @description Lado del mercado. */
                side: components["parameters"]["Side"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profundidad del mercado para el lado solicitado. */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketDepth"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getSignals: {
        parameters: {
            query: {
                /**
                 * @description Inicio del rango (RFC 3339, inclusive).
                 * @example 2026-07-10T00:00:00Z
                 */
                from: components["parameters"]["FromDateTime"];
                /**
                 * @description Fin del rango (RFC 3339, inclusive). Rango máximo de 90 días.
                 * @example 2026-07-17T00:00:00Z
                 */
                to: components["parameters"]["ToDateTime"];
                /**
                 * @description Filtro por tipo de señal. Vocabulario abierto por convención (definido en
                 *     `signal.v1`); catálogo en `knowledge/metrics/microestructura-p2p.md`.
                 */
                type?: components["parameters"]["SignalType"];
                /** @description Número de página (base 1). */
                page?: components["parameters"]["Page"];
                /** @description Tamaño de página. */
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de señales. */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableRange"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description El servicio está operativo (posiblemente degradado). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description El servicio no está operativo. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
